// /lib/constants.js

export const LEVELS = [
  { value: 'easy', label: 'Easy' },
  { value: 'intermediate', label: 'Intermediate' },
  { value: 'advanced', label: 'Advanced' }
];

export const VALID_LEVELS = new Set(LEVELS.map((l) => l.value));

export const SORT_CHOICES = [
  { value: 'random', label: 'Random' },
  // { value: 'latest', label: 'Latest' }, 
  { value: 'short', label: 'Short' },
  { value: 'long', label: 'Long' },
  { value: 'new', label: 'New' },
  { value: 'old', label: 'Old' }
];

export const COUNTRY_OPTIONS = [
  'Spain', 'Mexico', 'Argentina', 'Colombia', 'Chile', 'Various', 'Peru', 'Guatemala',
  'Uruguay', 'Dominican Republic', 'Venezuela', 'Costa Rica', 'Cuba', 'Ecuador',
  'Paraguay', 'Panama', 'Canary Islands', 'Puerto Rico', 'Equatorial Guinea',
  'Latin America'
].sort();

export const TAG_OPTIONS = [
  '80s',
  'acting',
  'animal',
  'animated stories',
  'anthropology',
  'ants',
  'archeology',
  'architecture',
  'art',
  'art history',
  'astronomy',
  'av',
  'baseball',
  'basketball',
  'boardgames',
  'books',
  'books, myths, legends',
  'boxing',
  'boxing history',
  'business',
  'business scandals',
  'calligraphy',
  'caravan',
  'challenge',
  'challenges',
  'chat',
  'chess',
  "children's history",
  "children's science",
  "children's stories",
  'chinese grammar',
  'climbing',
  'coffee',
  'comedy',
  'cooking',
  'crafts',
  'creepy',
  'creepy facts',
  'critiques',
  'crochet',
  'culture',
  'current events',
  'dallas cowboys',
  'debates',
  'design',
  'dramatized stories',
  'drawing',
  'dubbed show',
  'dubbing industry',
  'economy',
  'education',
  'facts',
  'film',
  'finance',
  'fitness',
  'food',
  'food reviews',
  'for learners',
  'futbol',
  'futbol discussion',
  'games',
  'gameshow',
  'gaming',
  'gardening',
  'geography',
  'geoguesser',
  'graphic design',
  'greek myths',
  'guitars',
  'harry potter disc',
  'health',
  'hip hop',
  'history',
  'hobby',
  'home design',
  "how it's made",
  'human mind',
  'humanities',
  'interviews',
  'journaling',
  'journalist',
  "kid's show",
  'kids',
  'kpop',
  'language learning',
  'law',
  'life',
  'life in canada',
  'life in china',
  'life in colombia',
  'life in cuba',
  'life in guatemala',
  'life in iceland',
  'life in japan',
  'life in korea',
  'life in mexico',
  'life in spain',
  'life in uruguay',
  'lifestyle',
  'lifestyle in australia',
  'lifestyle in germany',
  'lifestyle in japan',
  'lifestyle in mexico city',
  'literature',
  'makeup',
  'manufacturing',
  'martial arts',
  'math',
  'meditation',
  'mental health',
  'mindfullness',
  'minecraft',
  'minimalism',
  'montessori',
  'movie',
  'movie discussion',
  'movie reviews',
  'music',
  'music theory',
  'mystery',
  'mythology',
  'nasa',
  'native movie',
  'native show',
  'native story podcast',
  'nature',
  'nba history',
  'news',
  'organizing',
  'paranormal',
  'personal developement',
  'personal development',
  'philosophy',
  'photography',
  'physics',
  'politics',
  'pop culture',
  'positive affirmations',
  'product testing',
  'psychology',
  'psycology',
  'pyschology',
  'random',
  'random facts',
  're sales',
  'reality competition',
  'reality show',
  'relationships',
  'religion',
  'scary stories',
  'science',
  'skiing',
  'sobriety',
  'social experiment',
  'sports',
  'stories',
  'storytelling',
  'street interviews',
  'survival',
  'tarot',
  'taylor swift breakdown',
  'tech',
  'travel',
  'true crime',
  'tv ads',
  'video essays',
  'video game reviews',
  'videogame discussion',
  'videogames',
  'weather',
  'writing tips',
  'yoga'
].sort();
