// src/lib/constants/tags.js

export const TOP_TAGS = [
  "for learners",
  "lifestyle",
  "travel",
  "personal development",
  "cooking",
  "books",
  "food",
  "videogames",
  "history",
  "random facts",
  "science",
  "interviews",
  "fitness",
  "comedy",
  "true crime",
  "sports",
  "health",
  "movie reviews",
  "pop culture",
  "current events",
  "news",
  "life in japan",
  "music",
  "gardening",
  "business"
];

export const ALL_TAGS = [
  "80s",
  "acting",
  "animal",
  "animated stories",
  "anthropology",
  "ants",
  "archeology",
  "architecture",
  "art",
  "astronomy",
  "av",
  "baseball",
  "basketball",
  "boardgames",
  "books",
  "boxing",
  "boxing history",
  "business",
  "business scandals",
  "caravan",
  "challenge",
  "challenges",
  "chess",
  "children's history",
  "children's science",
  "children's stories",
  "chinese grammar",
  "climbing",
  "coffee",
  "comedy",
  "cooking",
  "crafts",
  "creepy",
  "creepy facts",
  "critiques",
  "crochet",
  "culture",
  "current events",
  "dallas cowboys",
  "debates",
  "dramatized stories",
  "dubbed show",
  "dubbing industry",
  "economy",
  "education",
  "facts",
  "film",
  "finance",
  "fitness",
  "food",
  "food reviews",
  "for learners",
  "futbol",
  "futbol discussion",
  "games",
  "gameshow",
  "gaming",
  "gardening",
  "geography",
  "geoguesser",
  "graphic design",
  "guitars",
  "harry potter disc",
  "health",
  "hip hop",
  "history",
  "hobby",
  "home design",
  "how it's made",
  "human mind",
  "humanities",
  "interviews",
  "journaling",
  "journalist",
  "kid's show",
  "kids show",
  "kpop",
  "language learning",
  "law",
  "life",
  "life in canada",
  "life in china",
  "life in colombia",
  "life in cuba",
  "life in guatemala",
  "life in iceland",
  "life in japan",
  "life in korea",
  "life in mexico",
  "life in spain",
  "life in uruguay",
  "lifestyle",
  "lifestyle in australia",
  "lifestyle in japan",
  "lifestyle in mexico city",
  "makeup",
  "manufacturing",
  "martial arts",
  "math",
  "meditation",
  "mental health",
  "mindfullness",
  "minecraft",
  "minimalism",
  "montessori",
  "movie",
  "movie discussion",
  "movie reviews",
  "music",
  "music theory",
  "mystery",
  "mythology",
  "nasa",
  "native show",
  "nature",
  "nba history",
  "news",
  "organizing",
  "paranormal",
  "personal developement",
  "personal development",
  "philosophy",
  "photography",
  "physics",
  "podcast",
  "politics",
  "pop culture",
  "positive affirmations",
  "product testing",
  "psychology",
  "psycology",
  "pyschology",
  "random",
  "random facts",
  "re sales",
  "relationships",
  "religion",
  "scary stories",
  "science",
  "skiing",
  "social experiment",
  "sports",
  "stories",
  "storytelling",
  "street interviews",
  "survival",
  "tarot",
  "taylor swift breakdown",
  "tech",
  "test",
  "travel",
  "true crime",
  "tv ads",
  "video essays",
  "video game reviews",
  "videogame discussion",
  "videogames",
  "weather",
  "writing tips",
  "yoga"
];
